app = "skynet-chat"
primary_region = "sin"

[build]
  builder = "paketo-buildpacks/python"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  STRIPE_API_KEY = "sk_test_..."
  STRIPE_PUBLIC_KEY = "pk_test_..."

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[services]]
  internal_port = 8765
  protocol = "tcp"
  [[services.ports]]
    port = 8765
