[phases.setup]
nixPkgs = ['python310', 'python3']
aptPkgs = ['build-essential', 'libpq-dev']
cmds = [
  'python3 -m venv venv',
  '. venv/bin/activate',
  'pip install --no-cache-dir -r requirements.txt',
  'pip install --no-cache-dir uvicorn'  # Instal uvicorn eksplisit
]

[phases.build]
cmds = ['python -m compileall .']

[start]
cmd = ". venv/bin/activate && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
