name: Push to Replit
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push to Replit
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.REPLIT_TOKEN }}" \
          -d '{"gitRepo": "https://github.com/apujiono/skynet-chat"}' \
          https://api.replit.com/v0/repls
